---
# ansible-role-autofs/tasks/setup_RedHat.yml


# Install using yum
- name: "Setup | RedHat | ensure autofs's package(s) present"
  yum:
    name: "{{ item }}"
    state: present
  with_items: autofs_pkg_names

